version: '3'
services:
  db:
    #Neuste Version mysql Image
    image: mysql:latest
    #wegen Error
    command: '--default-authentication-plugin=mysql_native_password'
    #startet Container neu, falls aus wegen error
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=Testuser
      - MYSQL_PASSWORD=wordpress
    # exposed Container port mysql
    expose:
      - 3306
  wordpress:
    image: wordpress:latest
    # host port mit Container port verbinden
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=Testuser
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress


  
    
